services:

  spark3-thrift:
    build:
      context: docker/spark/.
      dockerfile: docker/spark/Dockerfile
    ports:
      - "10000:10000"
      - "4040:4040"
    depends_on:
      - dbt-hive-metastore
    command: >
      --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
      --name Thrift JDBC/ODBC Server
    volumes:
      - ./.spark-warehouse/:/spark-warehouse/
      - ./docker/spark/hive-site.xml:/usr/spark/conf/hive-site.xml
      - ./docker/spark/spark-defaults.conf:/usr/spark/conf/spark-defaults.conf
    environment:
      - WAIT_FOR=dbt-hive-metastore:5432

  dbt-hive-metastore:
    image: postgres:9-alpine
    volumes:
      - ./.hive-metastore/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore